propiedad:
  ejemplo: Hola Docker


spring:
  datasource:
    url: jdbc:mysql://172.20.10.11:3306/clientes
    username: clientes
    password: '{cipher}307dd03b1615cfefcf98db707774ede0df6604bf535a8022fd444af765224a2e'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/