version: '3'

services:
  clientes:
    image: jcabelloc/clientes:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
  prestamos:
    image: jcabelloc/prestamos:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
